version: "3"
services:
  client:
    image: nginx
    ports:
      - 3000:80
    volumes:
      - ./front/dist:/usr/share/nginx/html
  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - database
  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    # ports:
    #   - 3000:3000
    depends_on:
      - backend
  database:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=0000
      - POSTGRES_DB=rh_solution
    ports:
      - 5432:5432
    volumes:
      - pgdb:/var/lib/postgresql/data


volumes:
  pgdb: