version: '3'

services:
  src:
    container_name: frontend_rh_solution
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/app/front
#     depends_on:
#       - backend_rh_solution
#       - db 
# include:
#   - ../back/docker-compose.yaml